/**
 * worker/strings.js — 动态板块 UI 文案 per locale（docs/英文版方案.md Phase 3）
 *
 * 覆盖 /tv /library /music /attractions /merchants 五个 Worker 渲染板块的界面文案
 * 与 html lang / 站点名 / manifest 等骨架字段。D1 内容（视频标题、商户简介、书名章节等）
 * 暂无双语字段 → EN 页回退显示中文原文（admin 双语录入后逐条替换，方案 §1.4）。
 *
 * prefix：该 locale 的站内链接前缀——动态页全部内链（含跨板块）都要挂前缀，
 * 跨到静态板块（如 /tourism）同样生效（静态板块已有 /en 产物）。
 */

export const LOCALES = {
  zh: { htmlLang: 'zh-CN', siteName: '焰境·万载', manifest: '/manifest.webmanifest', prefix: '' },
  en: { htmlLang: 'en', siteName: 'Whizzzest', manifest: '/en/manifest.webmanifest', prefix: '/en' },
};

const zh = {
  home: '首页',
  search: '搜索',
  crumbAria: '面包屑',

  tv: {
    cats: { drama: '短剧', fireworks: '烟花', heritage: '非遗', food: '美食', tourism: '文旅', other: '其他' },
    video: '视频',
    all: '全部',
    kicker: '万载TV · WANZHAI TV',
    heroTitle: '看万载 · 一屏看尽焰火人间',
    shelfTitle: '短剧剧场',
    allDrama: '全部短剧 →',
    epBadge: '更新至 {n} 集',
    epsTotal: '共 {n} 集',
    empty: '节目筹备中，敬请期待。',
    emptySub: '视频素材持续更新中 —— 短剧、烟花、非遗、美食，一屏看尽焰火人间。',
    featured: '本期焦点',
    watchPage: '观看页面 →',
    plays: '{n} 次播放',
    ep: '第{n}集',
    crumbTv: '万载TV',
    seriesEps: '本剧选集 · {name}',
    related: '相关视频',
    playAria: '播放：{title}',
    bilibili: 'B站观看 ↗',
    tabsAria: '视频分类',
    homeTitle: '万载TV — 万载视频频道：短剧 / 烟花 / 非遗 / 美食 | 焰境·万载',
    homeDesc: '万载TV 在线看：《一朝相逢便是万载》系列短剧、烟花晚会、非遗技艺、美食风物视频——一朝相逢，便是万载。',
    detailTitle: '{title} — 万载TV | 焰境·万载',
    detailDesc: '{title} —— 万载TV 视频在线观看。',
    ldDesc: '{title} — 万载TV 视频',
  },

  music: {
    unknown: '佚名',
    empty: '曲目录入中，敬请期待。',
    emptySub: '得胜鼓、纸棚山歌、开口傩……万载的声音正在路上。',
    kicker: '万载音乐 · WANZHAI MUSIC',
    heroTitle: '听万载 · 山歌鼓乐入焰来',
    sub: '{n} 首曲目 · 约 {m} 分钟 · 已播放 {p} 次',
    subNoDur: '{n} 首曲目 · 已播放 {p} 次',
    subNoPlays: '{n} 首曲目 · 约 {m} 分钟',
    subTracks: '{n} 首曲目',
    subEmpty: '万载的声音，正在路上',
    title: '万载音乐',
    waiting: '等待第一首曲目',
    clickToPlay: '点击曲目开始播放',
    playAria: '播放：{title}',
    play: '播放',
    pause: '暂停',
    download: '下载',
    downloadAria: '下载：{title}',
    share: '分享',
    shareAria: '分享：{title}',
    prevAria: '上一首',
    nextAria: '下一首',
    loopAria: '循环模式：列表循环',
    seekAria: '播放进度',
    volAria: '音量',
    homeTitle: '万载音乐 — 得胜鼓 / 纸棚山歌 / 开口傩 在线收听 | 焰境·万载',
    homeDesc: '万载音乐在线收听：得胜鼓、纸棚山歌、开口傩等万载民间音乐——山歌鼓乐入焰来，一朝相逢，便是万载。',
  },

  library: {
    cats: { novel: '小说', story: '故事', essay: '随笔', other: '其他' },
    searchPlaceholder: '搜索书名、简介、笔名…',
    searchAria: '搜索文库',
    all: '全部',
    unknown: '佚名',
    chapters: '{n} 章',
    words: '{n} 字',
    emptyQ: '没有找到含「{q}」的作品，换个关键词试试。',
    empty: '文库开荒中，首部作品即将上架。',
    emptySub: '你也可以在万载TV 看视频。',
    kicker: '焰境文库 · LIBRARY',
    heroTitle: '读万载的故事',
    heroSub: '本地作者笔下的烟花、古城与人间烟火——连载与图文，慢慢读。',
    ctaTitle: '你也想写万载的故事？',
    ctaDesc: '焰境文库向所有作者开放：注册作者账号，投稿你的小说、故事与随笔，审核通过即上线展示。',
    becomeAuthor: '成为作者',
    chapter: '第{n}章',
    tocEmpty: '章节即将上线，敬请期待。',
    pending: '另有 {n} 章更新审核中，通过后即可阅读。',
    updated: '{date} 更新',
    reads: '{n} 次阅读',
    startReading: '开始阅读',
    tocTitle: '目录（共 {n} 章）',
    toc: '目录',
    crumbLibrary: '文库',
    prevChapter: '上一章 ',
    nextChapter: '下一章 ',
    noPrev: '已是最新',
    noNext: '暂无',
    navAria: '章节切换',
    authorFallback: '焰境文库作者',
    tabsAria: '作品分类',
    homeTitle: '焰境文库 — 万载本地小说与图文连载 | 焰境·万载',
    homeDesc: '焰境文库：万载本地作者的小说、故事、随笔连载在线阅读——烟花、古城与人间烟火，慢慢读。',
    detailTitle: '{title} — 焰境文库 | 焰境·万载',
    detailDesc: '{title} —— 焰境文库在线阅读。',
    chTitle: '第{n}章 · {title} — {book} | 焰境文库',
    chDesc: '{book} 第{n}章在线阅读：{title}。',
  },

  attractions: {
    kicker: '旅游景点 · WANZHAI SCENERY',
    heroTitle: '游万载 · 古城山水焰火间',
    heroSub: '{n} 处景点 · 万载古城、竹山洞、九龙原始森林……一城焰火，满目山水',
    heroEmpty: '景点整理中，敬请期待',
    empty: '景点整理中，敬请期待。',
    emptySub: '万载古城、竹山洞、九龙原始森林……正在逐一上新。',
    crumbAttra: '旅游景点',
    infoAddress: '地址',
    infoHours: '开放时间',
    infoTickets: '门票',
    infoTransport: '交通',
    nearbyRoutes: '周边线路 · 旅游线路 →',
    relatedVideos: '万载视频 · 相关视频 →',
    prevItem: '上一处',
    nextItem: '下一处',
    allItems: '全部景点',
    pagerAria: '景点翻页',
    homeTitle: '旅游景点 — 万载古城 / 竹山洞 / 九龙原始森林 | 焰境·万载',
    homeDesc: '万载旅游景点推荐：万载古城、竹山洞、九龙原始森林、恒晖艺术农业、龙湖公园——古城山水焰火间，一朝相逢，便是万载。',
    detailTitle: '{name} — 万载旅游景点 | 焰境·万载',
    detailDesc: '{summary}——{name}旅游攻略、地址与交通，尽在焰境·万载。',
  },

  merchants: {
    cats: { food: '美食', stay: '住宿', specialty: '特产', fireworks: '花炮', other: '其他' },
    searchPlaceholder: '搜索商户名称、简介…',
    searchAria: '搜索商户',
    all: '全部',
    found: '找到 {n} 家含「{q}」的商户',
    clearSearch: '清除搜索',
    badgeFeatured: '推荐',
    badgeVerified: '认证商户',
    emptyQ: '没有找到含「{q}」的商户，换个关键词试试。',
    empty: '首批商户入驻审核中，敬请期待。',
    emptySub: '商家朋友想抢先展示？欢迎联系我们。',
    kicker: '焰境好店',
    heroTitle: '万载本地商户推荐',
    heroSub: '吃得地道、住得舒心、带得走的万载 —— 游客与本地人都在用。',
    ctaTitle: '你是万载的店家？',
    ctaDesc: '把你的店展示给每一位来万载的游客。基础展示免费；认证商户 ¥10/年（独立详情页 + 徽标 + 数据看板），置顶推荐 ¥15/年（目录页顶部大位）。',
    apply: '立即入驻',
    crumbMerchants: '商户',
    infoAddress: '地址',
    infoPhone: '电话',
    infoWechat: '微信',
    infoHours: '营业时间',
    copy: '复制',
    copied: '已复制',
    related: '同类好店',
    tabsAria: '商户分类',
    homeTitle: '焰境好店 — 万载本地商户推荐 | 焰境·万载',
    homeDesc: '焰境·万载精选本地好店：美食、住宿、特产、花炮，游客与本地人都在用的万载商户指南。商户入驻合作请联系我们。',
    detailTitle: '{name} — 焰境好店 | 焰境·万载',
  },
};

const en = {
  home: 'Home',
  search: 'Search',
  crumbAria: 'Breadcrumb',

  tv: {
    cats: { drama: 'Drama', fireworks: 'Fireworks', heritage: 'Heritage', food: 'Food', tourism: 'Culture & Tourism', other: 'Other' },
    video: 'Video',
    all: 'All',
    kicker: '万载TV · WANZHAI TV',
    heroTitle: 'Wanzai on screen — fireworks, drama and heritage in one place',
    shelfTitle: 'Drama series',
    allDrama: 'All drama →',
    epBadge: 'Up to ep. {n}',
    epsTotal: '{n} episodes',
    empty: 'New episodes are on the way.',
    emptySub: 'Fresh videos added continuously — drama, fireworks, heritage and food, all in one place.',
    featured: 'Featured',
    watchPage: 'Watch →',
    plays: '{n} plays',
    ep: 'Ep. {n}',
    crumbTv: 'Wanzai TV',
    seriesEps: 'Episodes · {name}',
    related: 'Related videos',
    playAria: 'Play: {title}',
    bilibili: 'Watch on Bilibili ↗',
    tabsAria: 'Video categories',
    homeTitle: 'Wanzai TV — drama, fireworks, heritage and food videos | Whizzzest',
    homeDesc: 'Watch Wanzai TV online: the "One Encounter, Ten Thousand Years" drama series, fireworks shows, heritage crafts and local food videos.',
    detailTitle: '{title} — Wanzai TV | Whizzzest',
    detailDesc: 'Watch "{title}" on Wanzai TV.',
    ldDesc: '{title} — Wanzai TV video',
  },

  music: {
    unknown: 'Unknown artist',
    empty: 'Tracks are being added — stay tuned.',
    emptySub: 'Desheng Drum, Zhipeng folk songs, Kaikou Nuo — the sounds of Wanzai are on their way.',
    kicker: '万载音乐 · WANZHAI MUSIC',
    heroTitle: 'Listen to Wanzai — folk songs and drums by the fireworks light',
    sub: '{n} tracks · about {m} min · {p} plays',
    subNoDur: '{n} tracks · {p} plays',
    subNoPlays: '{n} tracks · about {m} min',
    subTracks: '{n} tracks',
    subEmpty: 'The sounds of Wanzai, on their way',
    title: 'Wanzai Music',
    waiting: 'Waiting for the first track',
    clickToPlay: 'Select a track to start',
    playAria: 'Play: {title}',
    play: 'Play',
    pause: 'Pause',
    download: 'Download',
    downloadAria: 'Download: {title}',
    share: 'Share',
    shareAria: 'Share: {title}',
    prevAria: 'Previous track',
    nextAria: 'Next track',
    loopAria: 'Loop mode: repeat all',
    seekAria: 'Playback position',
    volAria: 'Volume',
    homeTitle: 'Wanzai Music — Desheng Drum, Zhipeng folk songs and more | Whizzzest',
    homeDesc: 'Listen to Wanzai folk music online: Desheng Drum, Zhipeng folk songs, Kaikou Nuo tunes and more.',
  },

  library: {
    cats: { novel: 'Novel', story: 'Story', essay: 'Essay', other: 'Other' },
    searchPlaceholder: 'Search titles, intros, pen names…',
    searchAria: 'Search the library',
    all: 'All',
    unknown: 'Unknown author',
    chapters: '{n} chapters',
    words: '{n} characters',
    emptyQ: 'No works matching "{q}" — try another keyword.',
    empty: 'The library is brand new — the first work is coming soon.',
    emptySub: 'Meanwhile, watch videos on Wanzai TV.',
    kicker: '焰境文库 · LIBRARY',
    heroTitle: 'Read Wanzai through local voices',
    heroSub: 'Fireworks, the ancient town and everyday life, written by local authors — serials and essays, at your own pace.',
    ctaTitle: 'Want to write your own Wanzai story?',
    ctaDesc: 'The library is open to all writers: register an author account and submit your fiction, stories and essays — approved works go live.',
    becomeAuthor: 'Become an author',
    chapter: 'Chapter {n}',
    tocEmpty: 'Chapters coming soon.',
    pending: '{n} more chapters are under review and will be readable once approved.',
    updated: 'Updated {date}',
    reads: '{n} reads',
    startReading: 'Start reading',
    tocTitle: 'Contents ({n} chapters)',
    toc: 'Contents',
    crumbLibrary: 'Library',
    prevChapter: 'Previous ',
    nextChapter: 'Next ',
    noPrev: 'This is the first chapter',
    noNext: 'No more chapters',
    navAria: 'Chapters',
    authorFallback: 'Whizzzest Library author',
    tabsAria: 'Categories',
    homeTitle: 'Whizzzest Library — fiction and essays from Wanzai | Whizzzest',
    homeDesc: 'The Whizzzest Library: novels, stories and essays by Wanzai authors, free to read — fireworks, the ancient town and everyday life.',
    detailTitle: '{title} — Whizzzest Library | Whizzzest',
    detailDesc: 'Read "{title}" in the Whizzzest Library.',
    chTitle: 'Chapter {n} · {title} — {book} | Whizzzest Library',
    chDesc: 'Read chapter {n} of {book}: {title}.',
  },

  attractions: {
    kicker: '旅游景点 · WANZHAI SCENERY',
    heroTitle: 'Discover Wanzai — ancient town, rivers and fireworks',
    heroSub: '{n} attractions — Wanzai Ancient City, Zhushan Cave, the Jiulong primeval forest…',
    heroEmpty: 'Attractions are being added — stay tuned',
    empty: 'Attractions are being added — stay tuned.',
    emptySub: 'Wanzai Ancient City, Zhushan Cave, the Jiulong primeval forest — more coming.',
    crumbAttra: 'Attractions',
    infoAddress: 'Address',
    infoHours: 'Opening hours',
    infoTickets: 'Tickets',
    infoTransport: 'Getting there',
    nearbyRoutes: 'Nearby routes · Tour routes →',
    relatedVideos: 'Wanzai videos · Related →',
    prevItem: 'Previous',
    nextItem: 'Next',
    allItems: 'All attractions',
    pagerAria: 'Attractions pager',
    homeTitle: 'Attractions — Wanzai Ancient City, Zhushan Cave and more | Whizzzest',
    homeDesc: 'Wanzai attractions: Wanzai Ancient City, Zhushan Cave, the Jiulong primeval forest, Henghui Art Agriculture, Longhu Park — ancient town, rivers and fireworks.',
    detailTitle: '{name} — Wanzai Attractions | Whizzzest',
    detailDesc: '{summary} — tips, address and transport for {name}, on Whizzzest.',
  },

  merchants: {
    cats: { food: 'Food & Drink', stay: 'Stay', specialty: 'Specialties', fireworks: 'Fireworks', other: 'Other' },
    searchPlaceholder: 'Search by name or intro…',
    searchAria: 'Search merchants',
    all: 'All',
    found: 'Found {n} merchants matching "{q}"',
    clearSearch: 'Clear search',
    badgeFeatured: 'Featured',
    badgeVerified: 'Verified',
    emptyQ: 'No merchants matching "{q}" — try another keyword.',
    empty: 'The first merchants are being onboarded — stay tuned.',
    emptySub: 'Run a business in Wanzai? Get in touch to be listed early.',
    kicker: 'Whizzzest Picks',
    heroTitle: 'Wanzai local business picks',
    heroSub: 'Eat well, stay well, take Wanzai home — the guide locals and travelers both use.',
    ctaTitle: 'Run a business in Wanzai?',
    ctaDesc: 'Show your shop to every visitor coming to Wanzai. Basic listings are free; Verified is ¥10/year (own detail page + badge + dashboard), Featured placement ¥15/year (top spot on the directory).',
    apply: 'Join now',
    crumbMerchants: 'Merchants',
    infoAddress: 'Address',
    infoPhone: 'Phone',
    infoWechat: 'WeChat',
    infoHours: 'Hours',
    copy: 'Copy',
    copied: 'Copied',
    related: 'Similar picks',
    tabsAria: 'Categories',
    homeTitle: 'Whizzzest Picks — Wanzai local business directory | Whizzzest',
    homeDesc: 'Hand-picked Wanzai businesses: food, stays, specialties and fireworks — the local guide travelers use too. Want in? Contact us.',
    detailTitle: '{name} — Whizzzest Picks | Whizzzest',
  },
};

export const UI = { zh, en };
